name = "podcasts"
version = "1.0.0"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
# description = ""
# licences = ["Apache-2.0"]
# repository = { type = "github", user = "", repo = "" }
# links = [{ title = "Website", href = "" }]
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
simplifile = ">= 2.2.0 and < 3.0.0"
glrss_parser = ">= 0.2.0 and < 1.0.0"
glemplate = ">= 8.0.0 and < 9.0.0"
tom = ">= 1.1.0 and < 2.0.0"
shellout = { git = "https://github.com/tynanbe/shellout.git", ref = "fdf9a86" }
gleam_http = ">= 3.7.0 and < 4.0.0"
# gleam_hackney = ">= 1.2.0 and < 2.0.0"
gleam_hackney = { path = "../hackney" }
sqlight = ">= 1.0.0 and < 2.0.0"
birl = ">= 1.8.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"

[javascript]
runtime = "deno"

[javascript.deno]
allow_read = true
allow_write = ["./rendered"]
